-- Run this once in Supabase SQL Editor.

create table if not exists public.hangout_responses (
    id bigint generated by default as identity primary key,
    selected_date text not null,
    selected_place text not null,
    selected_food text not null,
    created_at timestamptz not null default now()
);

alter table public.hangout_responses enable row level security;

create policy "Allow anonymous hangout submissions"
on public.hangout_responses
for insert
to anon
with check (true);

grant insert on public.hangout_responses to anon;
grant usage, select on sequence public.hangout_responses_id_seq to anon;
